<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name','metrazh','pipediameter', 'email', 'password','sanitation','phase','addedabbaha', 'sanitationfraction', 'servicescostfraction', 'companytype', 'userdebt', 'usercredit', 'sharednumber', 'telephone', 'businessid', 'nationalid',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::created(function ($user){
            $user->profile()->create([
                'title' => $user->name,
            ]);
        });

        static::created(function ($user){
            $user->specialisedservices()->create([
                'title' => 'تخلفات',
                'cost' => 0,
            ]);
        });
    }

    public function profile()
    {
        return $this->hasOne(Profile::class);
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }

    public function debts()
    {
        return $this->hasMany(Debt::class);
    }

    public function specialisedservices()
    {
        return $this->hasMany(SpecialisedService::class);
    }

    public function payments()
    {
        return $this->hasMany(Payment::class);
    }

}
